### ISSUE TITLE
If node turns non-primary and then primary again with desync on latter will result in crash

### ISSUE THREAD

**Issue by kbauskar** [mariadb-corporation/mysql-wsrep#276] opened 2016-08-18 09:02 UTC
1. Start 2 node cluster
2. Execute wsrep_desync = 1 on node-2. Node state is changed to DONOR/DESYNCED.
3. Now force node-2 to become non-primary while it is in donor/desync state (simply setting global.wsrep_cluster_address = '') should help.
4. Ensure node-2 is non-primary by checking the state.
5. Resume node-2 to become primary by resetting the cluster_address.
   "SET @@global.wsrep_cluster_address = 'valid value';"

In process to become primary again following assert it seen:

(gdb) bt
#0  0x00007ffff67b0267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff67b1eca in __GI_abort () at abort.c:89
#2  0x00007ffff67a903d in __assert_fail_base (fmt=0x7ffff690b028 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fffdd1aa392 "node->desync_count > 0", file=file

@entry=0x7fffdd1aa280 "gcs/src/gcs_node.cpp", line=line@entry=179, function=function@entry=0x7fffdd1aa580 <gcs_node_update_status(gcs_node_, gcs_state_quorum const_)::**PRETTY_FUNCTION**

> "void gcs_node_update_status(gcs_node_t_, const gcs_state_quorum_t_)") at assert.c:92
> # 3  0x00007ffff67a90f2 in __GI___assert_fail (assertion=0x7fffdd1aa392 "node->desync_count > 0", file=0x7fffdd1aa280 "gcs/src/gcs_node.cpp", line=179, function=0x7fffdd1aa580 <gcs_node_u
> 
> pdate_status(gcs_node_, gcs_state_quorum const_)::**PRETTY_FUNCTION**> "void gcs_node_update_status(gcs_node_t_, const gcs_state_quorum_t_)") at assert.c:101
> # 4  0x00007fffdd0fca6f in gcs_node_update_status (node=0x7fffc0011d48, quorum=0x1a04ed0) at gcs/src/gcs_node.cpp:179
> # 5  0x00007fffdd0fdb9a in group_post_state_exchange (group=0x1a04e20) at gcs/src/gcs_group.cpp:307
> # 6  0x00007fffdd0fee33 in gcs_group_handle_state_msg (group=0x1a04e20, msg=0x1a04e00) at gcs/src/gcs_group.cpp:587
> # 7  0x00007fffdd104d01 in core_handle_state_msg (core=0x1a04da0, msg=0x1a04e00, act=0x7fffd23c6ec0) at gcs/src/gcs_core.cpp:909
> # 8  0x00007fffdd1055a0 in gcs_core_recv (conn=0x1a04da0, recv_act=0x7fffd23c6ec0, timeout=9223372035999999999) at gcs/src/gcs_core.cpp:1093
> # 9  0x00007fffdd10ad29 in gcs_recv_thread (arg=0x1a04bb0) at gcs/src/gcs.cpp:1191
> # 10 0x00007ffff73796aa in start_thread (arg=0x7fffd23c7700) at pthread_create.c:333
> # 11 0x00007ffff6881eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Validated with 5.6.31 release.

TCs:

galera_non_prim_when_desynced.test
# 
# 

--source include/galera_cluster.inc
--source include/have_innodb.inc

--connection node_2
SET SESSION wsrep_sync_wait=0;
SET @@global.wsrep_desync = 1;
# 

--let $wsrep_cluster_address_saved = `SELECT @@global.wsrep_cluster_address`
SET @@global.wsrep_cluster_address = '';
SHOW STATUS LIKE 'wsrep_ready';
SHOW STATUS LIKE 'wsrep_cluster_status';
# 

--disable_query_log
--eval SET @@global.wsrep_cluster_address = '$wsrep_cluster_address_saved'
--enable_query_log
--source include/wait_until_connected_again.inc
SHOW STATUS LIKE 'wsrep_ready';
## SHOW STATUS LIKE 'wsrep_cluster_status';

TC credit: Julius

**Comment by ayurchen** [comment] 2016-08-20 14:50
Duplicate of https://github.com/codership/mysql-wsrep/issues/278

**Closed as completed by ayurchen** 2016-08-20 14:50 UTC
Labels: duplicate
