### ISSUE TITLE
Assertion `key_count > 0' failed in galera::Certification::do_test_v3() with MyISAM and Stored Procedure

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#13] opened 2014-11-13 11:25 UTC
All InnoDB tests now assert as follows:

```
mysqld: galera/src/certification.cpp:590: galera::Certification::TestResult galera::Certification::do_test_v3(galera::TrxHandle*, bool): Assertion `key_count > 0' failed.

#7  0x0000003e9042da82 in __assert_fail () from /lib64/libc.so.6
#8  0x00007f4a3d6e7aea in galera::Certification::do_test_v3 (this=this@entry=0x2603f58, trx=trx@entry=0x7f4a0001e2a0, store_keys=store_keys@entry=true) at galera/src/certification.cpp:590
#9  0x00007f4a3d6e9b03 in galera::Certification::do_test (this=0x2603f58, trx=trx@entry=0x7f4a0001e2a0, store_keys=<optimized out>) at galera/src/certification.cpp:747
#10 0x00007f4a3d6e9e29 in galera::Certification::test (this=<optimized out>, trx=0x7f4a0001e2a0, bval=<optimized out>) at galera/src/certification.cpp:916
#11 0x00007f4a3d6e9f45 in galera::Certification::append_trx (this=this@entry=0x2603f58, trx=trx@entry=0x7f4a0001e2a0) at galera/src/certification.cpp:1024
#12 0x00007f4a3d728199 in galera::ReplicatorSMM::cert (this=0x26035a0, trx=0x7f4a0001e2a0) at galera/src/replicator_smm.cpp:1689
#13 0x00007f4a3d71e633 in galera::ReplicatorSMM::cert_and_catch (this=this@entry=0x26035a0, trx=trx@entry=0x7f4a0001e2a0) at galera/src/replicator_smm.cpp:1774
#14 0x00007f4a3d71f1f7 in galera::ReplicatorSMM::to_isolation_begin (this=0x26035a0, trx=0x7f4a0001e2a0, meta=<optimized out>) at galera/src/replicator_smm.cpp:1010
#15 0x00007f4a3d735ccb in galera_to_execute_start (gh=<optimized out>, conn_id=7, keys=<optimized out>, keys_num=<optimized out>, data=0x7f4a30793970, count=1, meta=0x2856920) at galera/src/wsrep_provider.cpp:729
#16 0x000000000063e142 in wsrep_TOI_begin (thd=0x2854870, db_=0x0, table_=0x0, table_list=0x7f4a00043718) at /home/philips/git/mysql-wsrep/sql/wsrep_mysqld.cc:1269
#17 0x000000000063f067 in wsrep_to_isolation_begin (thd=0x2854870, db_=0x0, table_=0x0, table_list=0x7f4a00043718) at /home/philips/git/mysql-wsrep/sql/wsrep_mysqld.cc:1443
#18 0x00000000007f42a4 in mysql_execute_command (thd=0x2854870) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:3997
#19 0x000000000099953e in sp_instr_stmt::exec_core (this=0x7f4a00043c90, thd=0x2854870, nextp=0x7f4a307950b8) at /home/philips/git/mysql-wsrep/sql/sp_instr.cc:901
#20 0x00000000009983a0 in sp_lex_instr::reset_lex_and_exec_core (this=0x7f4a00043c90, thd=0x2854870, nextp=0x7f4a307950b8, open_tables=false) at /home/philips/git/mysql-wsrep/sql/sp_instr.cc:390
#21 0x0000000000998cae in sp_lex_instr::validate_lex_and_execute_core (this=0x7f4a00043c90, thd=0x2854870, nextp=0x7f4a307950b8, open_tables=false) at /home/philips/git/mysql-wsrep/sql/sp_instr.cc:638
#22 0x00000000009991cd in sp_instr_stmt::execute (this=0x7f4a00043c90, thd=0x2854870, nextp=0x7f4a307950b8) at /home/philips/git/mysql-wsrep/sql/sp_instr.cc:808
#23 0x000000000074df46 in sp_head::execute (this=0x7f4a000924c0, thd=0x2854870, merge_da_on_success=true) at /home/philips/git/mysql-wsrep/sql/sp_head.cc:645
#24 0x000000000074fc6a in sp_head::execute_procedure (this=0x7f4a000924c0, thd=0x2854870, args=0x2857820) at /home/philips/git/mysql-wsrep/sql/sp_head.cc:1315
#25 0x00000000007f79d9 in mysql_execute_command (thd=0x2854870) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:4987
#26 0x00000000007fc9b9 in mysql_parse (thd=0x2854870, rawbuf=0x7f4a00081650 "call mtr.check_warnings(@result)", length=32, parser_state=0x7f4a30796730) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6815
#27 0x00000000007fbf7a in wsrep_mysql_parse (thd=0x2854870, rawbuf=0x7f4a00081650 "call mtr.check_warnings(@result)", length=32, parser_state=0x7f4a30796730) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6595
#28 0x00000000007edbc7 in dispatch_command (command=COM_QUERY, thd=0x2854870, packet=0x291d631 "call mtr.check_warnings(@result)", packet_length=32) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1525
#29 0x00000000007ec687 in do_command (thd=0x2854870) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1114
#30 0x00000000007b58a2 in do_handle_one_connection (thd_arg=0x2854870) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:1007
#31 0x00000000007b53b7 in handle_one_connection (arg=0x2854870) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:916
#32 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#33 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

To reproduce:

```
mysql-test-run.pl --suites=innodb --mysqld=--performance-schema=OFF --mysqld=--wsrep-cluster-address="gcomm://" --mysqld=--wsrep-provider=/home/philips/git/galera/libgalera_smm.so --skip-test-list=suite/innodb/t/galera.skip
```

**Comment by sjaakola** [comment] 2014-11-13 11:27
Looks like a duplicate of #11

**Comment by philip-galera** [comment] 2014-11-13 11:30
#11 is MyISAM  + Stored procedures, #13 is CREATE + DROP + InnoDB . I suspect the same assertion is being hit by two different code paths.

**Comment by sjaakola** [comment] 2014-11-13 12:07
Pushed a fix to skip TOI replication, if all tables are temporary

**Closed as completed** 2014-11-13 12:08 UTC
Labels: 3 - Done
